In [9]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
df = pd.read_csv('data.csv')

In [16]:
df.head(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

## Data Cleaning

In [18]:
# fillna
# dropna
df.dropna(how='any', inplace=True)

In [19]:
len(df)

569

In [20]:
df.diagnosis.value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [22]:
df.diagnosis.value_counts()/len(df)*100


diagnosis
B    62.741652
M    37.258348
Name: count, dtype: float64

## Splitting the data into X & Y

In [23]:
X = df.drop(['id', 'diagnosis'], axis=1)

In [25]:
Y = df.diagnosis.values

## **Train Test Split**

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.25)

In [28]:
len(X_train)

426

In [29]:
len(X_test)

143

## Feature Scaling 

In [30]:
from sklearn.preprocessing import StandardScaler

sc= StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [31]:
X_train_sc

array([[ 0.55033599, -0.76356357,  0.56087187, ...,  0.10512066,
         0.36513899,  0.26187569],
       [ 0.10148918,  0.47917204,  0.19593127, ...,  2.32317359,
         2.08868885,  2.27561524],
       [-1.55105749, -0.81818931, -1.51054579, ..., -0.20234736,
         0.01298254,  0.90478463],
       ...,
       [-1.26424721, -0.06936144, -1.2605471 , ..., -1.10654811,
         0.43184704, -0.24341885],
       [ 0.23134424, -0.61106671,  0.25011817, ..., -0.2512975 ,
        -1.14897861,  0.04349919],
       [-1.14624848,  0.03761397, -1.14560518, ..., -1.46709644,
        -1.01711386, -0.91661357]])

In [32]:
X_test_sc

array([[ 0.71124334,  0.49282848,  0.71686448, ...,  0.96480738,
         3.0179475 ,  0.08813088],
       [-0.78773563, -0.48133057, -0.77902255, ..., -0.82921501,
        -0.51757916, -0.19719316],
       [ 1.46214429, -0.28331226,  1.41883123, ...,  1.63634203,
         1.04307894, -0.36137404],
       ...,
       [ 0.24263598,  1.43739858,  0.22015117, ...,  0.52578587,
        -0.40898466,  0.51585129],
       [ 0.0789057 , -1.94256914,  0.06744262, ...,  0.05922991,
        -0.04441741, -0.24501284],
       [ 1.15444428,  0.26294515,  1.15610683, ...,  0.50131081,
         0.24258234, -0.32099298]])

## Model Building 

In [35]:
from sklearn.neighbors import KNeighborsClassifier

# Intitiate the Classifier
model_knn = KNeighborsClassifier()

# Passing the data to classifier
model_knn.fit(X_train_sc, Y_train)

KNeighborsClassifier()

**In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org**.

In [36]:
Y_pred_knn = model_knn.predict(X_test_sc)

In [37]:
Y_pred_knn

array(['M', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'M',
       'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B',
       'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B',
       'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M',
       'M', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'M', 'B', 'M'],
      dtype=object)

In [38]:
Y_test

array(['M', 'B', 'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'M',
       'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B',
       'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B',
       'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'M',
       'M', 'M', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'M', 'B', 'M'],
      dtype=object)

In [39]:
# Classification metrics to check how the model behaves

from sklearn.metrics import accuracy_score

print(round(accuracy_score(Y_test, Y_pred_knn)*100,2))

94.41


## Model Building - DT

In [40]:

from sklearn.tree import DecisionTreeClassifier

# Initiate the classifier
model_dt = DecisionTreeClassifier()

# Passing the data to classifier
model_dt.fit(X_train_sc, Y_train)

DecisionTreeClassifier()

**In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.**

In [42]:
Y_pred_dt = model_dt.predict(X_test_sc)

In [43]:

# Classification metrics to check how the model behaves

from sklearn.metrics import accuracy_score

print(round(accuracy_score(Y_test, Y_pred_dt)*100,2))

94.41


## Model Building - RF

In [44]:
from sklearn.ensemble import RandomForestClassifier

# Initiate the classifier
model_rf = RandomForestClassifier()

# Passing the data to classifier
model_rf.fit(X_train_sc, Y_train)

RandomForestClassifier()

**In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org**.

In [45]:
Y_pred_rf = model_rf.predict(X_test_sc)

In [46]:
# Classification metrics to check how the model behaves

from sklearn.metrics import accuracy_score

print(round(accuracy_score(Y_test, Y_pred_rf)*100,2))

94.41


## Model Building - NB

In [47]:
from sklearn.naive_bayes import GaussianNB

# Initiate the classifier
model_nb = GaussianNB()

# Passing the data to classifier
model_nb.fit(X_train_sc, Y_train)

GaussianNB()

**In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org**.

In [48]:
Y_pred_nb = model_nb.predict(X_test_sc)

In [49]:
# Classification metrics to check how the model behaves

from sklearn.metrics import accuracy_score

print(round(accuracy_score(Y_test, Y_pred_nb)*100,2))

95.1


##  Predict for a new patient

In [50]:
new_data = [[22.57,16.77,121.9,1326,0.08474,0.07864,0.0969,0.07017,0.1812,
             0.05667,0.5435,0.7339,3.398,74.08,0.105225,0.01308,0.0186,0.0234,
             0.01389,0.003532,23.99,23.41,158.8,1956,0.2238,0.1866,0.2416,0.186,0.275,0.09902]]

In [51]:
new_data_sc = sc.transform(new_data)

C:\Users\User\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [52]:
new_data_sc

array([[ 2.35701497e+00, -6.04238488e-01,  1.20126259e+00,
         1.89654615e+00, -8.28914671e-01, -5.19374794e-01,
         6.41354306e-02,  5.21173798e-01, -1.65680972e-02,
        -8.67962982e-01,  5.46035022e-01, -8.67747919e-01,
         2.89173393e-01,  8.25510165e-01,  3.07283969e+01,
        -7.12742538e-01, -5.10608943e-01,  1.86043916e+00,
        -7.59839313e-01, -1.04917383e-01,  1.58604011e+00,
        -3.97223520e-01,  1.53332467e+00,  1.91821924e+00,
         3.97391205e+00, -4.73459582e-01, -2.06649909e-01,
         1.03670289e+00, -2.60055059e-01,  7.62388268e-01]])

In [53]:
Y_pred_single = model_knn.predict(new_data_sc)

In [54]:
Y_pred_single

array(['B'], dtype=object)

In [55]:
new_data_1 = [[20.57,17.77,132.9,1326,0.08474,0.07864,0.0869,0.07017,0.1812,
               0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.0186,
               0.0134,0.01389,0.003532,24.99,23.41,
               158.8,1956,0.1238,0.1866,0.2416,0.186,0.275,0.08902]]

In [56]:
new_data_1_sc = sc.transform(new_data_1)
Y_pred_single2 = model_knn.predict(new_data_1_sc)

C:\Users\User\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [57]:
Y_pred_single2

array(['M'], dtype=object)